### ISSUE TITLE
Cities In Lake Hexes

### ISSUE THREAD

**Issue by Mochnant** [nedbrek/Atlantis#12]
It is possible for cities to be places in lake hexes, and they are enter-able without a ship.

```
lake (25,7) in Baifelgris, contains Tar-ungol [city], 4746 peasants
  (hobbits), $52206.
------------------------------------------------------------
  The weather was clear last month; it will be clear next month.
  Wages: $21 (Max: $19933).
  Wanted: 178 grain [GRAI] at $24, 104 livestock [LIVE] at $24, 74
    iron [IRON] at $42, 72 herbs [HERB] at $48, 88 plate armor [PARM]
    at $473, 21 yew [YEW] at $164, 39 mithril armor [MARM] at $896, 95
    hammers [HAMM] at $104, 39 magic wagons [MWAG] at $441, 55 cloth
    armor [CLAR] at $63, 33 mushrooms [MUSH] at $204, 50 daggers
    [DAGG] at $65, 62 spices [SPIC] at $293, 66 mink [MINK] at $288.
  For Sale: 86 horses [HORS] at $54, 52 picks [PICK] at $98, 68 spears
    [SPEA] at $102, 36 axes [AXE] at $93, 30 parrying daggers [PDAG]
    at $78, 91 figurines [FIGU] at $102, 91 vodka [VODK] at $93, 949
    hobbits [HOBB] at $84.
  Entertainment available: $2610.
  Products: 86 grain [GRAI], 11 horses [HORS], 18 fish [FISH].

Exits:
  North : forest (25,5) in Asay.
  Northeast : forest (26,6) in Asay.
  Southeast : lake (26,8) in Baifelgris.
  South : lake (25,9) in Baifelgris.
  Southwest : lake (24,8) in Baifelgris.
  Northwest : forest (24,6) in Asay.

- City Guard (11), on guard, 120 leaders [LEAD], 120 swords [SWOR].
```

**Comment by Mochnant** [comment]
This actually looks to be related to a very odd Ceran lake configuration, which should probable be removed.

https://github.com/Atlantis-PBEM/Atlantis/blob/master/gamedata.cpp#L4410-L4418
```
	{"lake", "ceran_lake", 'l', R_CERAN_LAKE,
	 TerrainType::FLYINGMOUNTS,
	 800,18,50,1,
	 {{I_HORSE,100,10},{I_WHORSE,45,5},{I_FISH,100,10},{I_MUSHROOM,10,10},
	  {-1,0,0},{-1,0,0},{-1,0,0}},
	 {I_PLAINSMAN,I_HOBBIT,I_HIGHELF,I_GNOME},
	 {I_VIKING,I_HOBBIT,I_FAIRY},
	 4,I_LION,I_ETTIN,I_CENTAUR,
	 10,{O_RUIN,O_CRYPT,O_LAIR,-1,-1,-1}},
```

**Comment by nedbrek** [comment]
It's hard to tell what the original intent was.  Is this a city literally built on a lake (ala Bard's Lake Town)?  Or is it a region with a lot of lakes (ala northern Michigan or Minnesota)?

If it is the first, then a multi-region lake is kind of weird.  It's really an ocean.  However, the second interpretation could make sense (a "land of a thousand lakes")...

**Comment by nedbrek** [comment]
It's probably a good idea to add something to the rules, to let players know they can walk in lake regions (which is not obvious)

**Comment by Mochnant** [comment]
I'd assume remove the lake entirely.  It may have been the intend to try and indicate this is a land hex with a lot of small lakes, but the hex is simply called "lake" and even gets water borders drawn around it.

Instead of confusing the issue, it is more clear to remove it entirely.
