### ISSUE TITLE
Feature:  Limited Repeat With @ Command

### ISSUE THREAD

**Issue by Mochnant** [nedbrek/Atlantis#14]
Current behavior is that the @ symbol causes a command to repeat indefinitely.

Example:
```
@ study combat
```

New functionality would be @ plus a #, indicating the turns to execute the order.

Example:
```
@3 study combat
```

During turn processing, the count will be decremented and put back on the orders sheet.

Normal flow:
```
@3 study combat
```
```
@2 study combat
```
```
@1 study combat
```
```
; order does not appear on next turn
```

The @1 functionality is equivalent to this:
```
study combat
```

**Comment by nedbrek** [comment]
I'm going to use this in my test game right away, it's great!
