### ISSUE TITLE
Update @ orders for "new N"

### ISSUE THREAD

**Issue by nedbrek** [nedbrek/Atlantis#16]
It would be nice to have a teacher issue "@3 teach new 1".  However, the "new 1" would change target each turn.  I spend a lot of time going through units and figuring out who "new 1" has become.

The end result would be:
turn 1: @3 teach new 1
turn 2: @2 teach 1546
turn 3: teach 1546
turn 4: 1546 is ready to go

**Comment by Mochnant** [comment]
Would this perhaps be better to work into the more general alias solution in #11 ?

**Comment by nedbrek** [comment]
There's some overlap.  If I want to fire off a quick group, then "form Mini; teach mini" is handy.  But, for continuous pipelines of training, this will make things much easier.

**Comment by nedbrek** [comment]
Implemented in 9fd556886757
