### ISSUE TITLE
PRODUCE Should Allow Quantity Argument

### ISSUE THREAD

**Issue by Mochnant** [nedbrek/Atlantis#3]
The Produce command should allow you to specify an optional argument for maximum to produce.

Current:
PRODUCE [item] 

Proposed:
PRODUCE [item]   (produces maximum as currently does)
    or
PRODUCE [quantity] [item]

Quantity should be optional and default to MAX for backwards compatibility, if possible.

With the potential for extra unused production, the ability to stack a few PRODUCE commands for the same unit would be useful.

PRODUCE 5 SWORD
PRODUCE 2 PICK
PRODUCE SPEAR

This would produce 5 swords, 2 picks, and as many spears as there are men/materials.

**Comment by nedbrek** [comment]
Fixed in commit 660763f356f301172a249

**Comment by nedbrek** [comment]
I went with "PRODUCE <item> LIMIT <quantity>" to prevent any overlap with the unlimited version.

**Comment by Mochnant** [comment]
Sounds good!
