### ISSUE TITLE
DECLARE Faction Alignment

### ISSUE THREAD

**Issue by Mochnant** [nedbrek/Atlantis#36]
As alignment is currently permanent once selected by recruiting a race, it would be helpful to allow players to declare and set an alignment to prevent accidentally recruiting from a race and setting your alignment, as it is not possible to see race alignments before recruiting them.

A possible option:

```DECLARE ALIGNMENT <faction> GOOD```

**Comment by Mochnant** [comment]
As an addition to this, we could prevent recruiting good or evil until a faction is declared, which would prevent accidentally setting alignment.

**Comment by nedbrek** [comment]
This was implemented in d3942aea78f251af125e1d23c68
