### ISSUE TITLE
Random Initial Player Placement Without Nexus

### ISSUE THREAD

**Issue by Mochnant** [nedbrek/Atlantis#41]
Currently there is support for 2 non-exclusive, initial placement options:
- directional exits from the Nexus (6 starting cities)
- casting to an overworld gate (~15 random gates)

Add a new exclusive option that places each new player in a random, non-guarded, non-produced, non-lair, non-wandering monster occupied hex.  Players would never see the Nexus in this configuration.

If one cannot be located, fall back to picking a random hex with a gate in it (as if they had CAST GATE RANDOM).

**Comment by Mochnant** [comment]
Atlantis 5.x seems to do this via showing generic terrains in the Nexus and picking a random example of that terrain type when units move in that direction.

**Comment by nedbrek** [comment]
I believe I can do this using k-means clustering. It could even be done with a script and players.in, so it wouldn't be in the core code (giving us more flexibility)...

**Comment by nedbrek** [comment]
Commit 7b7d75f48d1d4de2d0 implements `CAST GATE ALIGNMENT` which will take a unit to an empty hex with the race matching their alignment (not neutral).

**Comment by nedbrek** [comment]
(That is, the player must declare a non-neutral alignment - the hex might be neutral)

**Comment by Mochnant** [comment]
This FR has been completed!  Nice job, @nedbrek!
