### ISSUE TITLE
SKILL_PRACTISE_AMOUNT Gained Is Never Reported

### ISSUE THREAD

**Issue by Mochnant** [nedbrek/Atlantis#5]
When using a skill and receiving the SKILL_PRACTISE_AMOUNT, a unit should receive a message showing the amount gained and in what skill.  This would be especially helpful in magic where the skill affected is not always obvious.

SKILL_PRACTISE_AMOUNT=5

Farmer (281): Produces 5 grain [GRAI] in plain (20,26) in Lilnon.
Farmer (281): Gains skill in farming (+5).
OR Farmer (281): Gets practice in farming (+5).
OR Farmer (281): Gains experience in farming (+5).

The exact verbiage is not important.

**Comment by nedbrek** [comment]
Events during turn:
Unit (87): Claims $820.
Unit (87): Buys 10 high elves [HELF] at $72 each.
Unit (80): Teaches combat to Unit (87).
Unit (80): Gets practice in combat (+5).
Unit (87): Studies combat.
Unit (80): Claims 20 silver for maintenance.
Unit (87): Claims 100 silver for maintenance.
