### ISSUE TITLE
New Weapon - Sling

### ISSUE THREAD

**Issue by odrium** [nedbrek/Atlantis#58]
Proposing a "sling" weapon which is produced by Weaponsmith at level 1, uses 1 herb to produce, and takes 1 month.  Alternatively could be produced by Herb Lore at 2, same as a bag.

I think it would add interest in the early game, and any weapon that isn't dependent on iron (or to a lesser degree, wood) broadens the tech tree in weapons.

Extra bonus if slings have a 1% chance to one-shot giants . . . . just for Biblical accuracy . . .

**Comment by nedbrek** [comment]
I assume there is no skill needed to use?

The base game has javelin, which is a missile weapon with no skill to use. It's disabled in miskatonic.

**Comment by odrium** [comment]
No skill I would think. Unless something odd like Hunting 1.

**Comment by nedbrek** [comment]
This is possible with the current game engine. Just create a missile weapon with no skill required (like JAVE)
