### ISSUE TITLE
Feature:  Good/Evil Factions

### ISSUE THREAD

**Issue by Mochnant** [nedbrek/Atlantis#8]
An optional "faction alignment" that prevents a faction from recruiting races of the opposite alignment.  Neutral races could work either side.

Optional enslavement for good races by evil factions (perhaps with a -1 max skill level).

Races would likely need their skills balanced to prevent good or evil having an unfair advantage.

**Comment by nedbrek** [comment]
I have a patch for this in a private repo.  I have delayed moving it over mostly because of the balancing issue...

**Comment by Mochnant** [comment]
What's are the rules?  I'd be happy to do a pass of the skills if I know what the parameters of the new good/evil dynamic are.

**Comment by nedbrek** [comment]
The way I coded it, factions start neutral.  Buying a man-type of good or evil sets your faction accordingly.  Attempting to buy a man-type of the opposing type would generate an error.

**Comment by Mochnant** [comment]
Do you have a breakdown of which way the races fell?

**Comment by nedbrek** [comment]
Should be fixed with 76d73419637
